### PR TITLE
Fixes tests clippy ci

### PR DESCRIPTION
**Pull request by Fishrock123**
@rousan Hi, I'm considering using multer-rs in a rebase of https://github.com/http-rs/http-types/pull/175 - i.e. multipart support for http-rs (Tide & Surf), hope these fixes are welcome!

_(Along with this, I'm going to be looking at adding support here for `futures::io::AsyncRead` & friends as a build feature, and also possibly a build feature for using http-types instead of http.)_

### CODE REVIEW

**Comment by rousan** [comment]
Hey, @Fishrock123 , thank you very much for your PR. I'm definitely looking forward to make this crate more clean and adding supports to be able to use it in any future executors (tokio or async-std).

So, here, the following constructs will have two different variants:

AsyncRead
- from `tokio::io::AsyncRead`
- from `futures::io::AsyncRead`

and possibly for Http primitives:
- from `http`
- from `http-types`

And these could be configured using build features.

**Comment by rousan** [comment]
Also, as we develop any features and bug fixes in `develop` branch, could you please send the PR to `develop` branch instead of `master`.

**Comment by Fishrock123** [comment]
Should I re-target this PR?

**Comment by rousan** [comment]
> Should I re-target this PR?

Yes, to the `develop` branch.

**Comment by Fishrock123** [comment]
It's honestly quite confusing that the primary branch is not the development branch, btw.

**Comment by rousan** [comment]
> It's honestly quite confusing that the primary branch is not the development branch, btw.

It's just a development pattern. We use `master` branch for the latest stable code and `develop` for on-going unstable code.

**Pull request merged**
