### PR TITLE
Update to tokio 1.0.

### PR DESCRIPTION
**Pull request by SergioBenitez**
Also updates hyper to 0.14 in dev-dependencies. Disables the 'routerify' example, presumably temporarily, as it is not compatible with tokio 1.0 or hyper 0.14.

### CODE REVIEW

**Comment by rousan** [comment]
@SergioBenitez, as we use `develop` branch for development purpose, can you please send the PR to `develop` branch?

**Comment by rousan** [comment]
Hey @SergioBenitez, I want you to be an active maintainer for this repo as I don't get enough time to maintain it properly. I invited you on Github to be a collaborator. Let me know your response.

**Comment by SergioBenitez** [comment]
Sounds good. Happy to help. Will let you know if this changes.

**Comment by nitsky** [comment]
@rousan Would you mind publishing a new release with the tokio v1 support? Thank you!

**Comment by rousan** [comment]
Okay, I will make a new minor release today.

**Comment by dbrgn** [comment]
Thanks @rousan and @SergioBenitez for working on this!

**Comment by rousan** [comment]
@SergioBenitez, I couldn't get time to release the major version, do let me know if the master branch has the stable code, so that I can release with latest version of Tokio and Hyper.

**Comment by nitsky** [comment]
@rousan I have been using the code on master successfully with tokio v1 and hyper v0.14

**Comment by SergioBenitez** [comment]
@rousan Yes, it's stable. I was hoping to review and merge at least #29 before the new release, but that should be semver compatible at should the rest of the PRs.

**Comment by rousan** [comment]
Okay, then we will release after merging that PR.

**Comment by nitsky** [comment]
Now that #29 has merged, are there any other blockers to releasing a version that supports tokio v1?

**Pull request merged**
