### PR TITLE
Reexport Bytes from the crate root

### PR DESCRIPTION
**Pull request by Koxiaet**
This means that users won't have to depend on bytes in some cases.

### CODE REVIEW

**Comment by rousan** [comment]
Can you send the PR to develop branch? Then we will make a release.

**Comment by Koxiaet** [comment]
I've changed the base branch, but merging this will also merge all the `master` commits into the `develop` branch, is that fine?

**Comment by rousan** [comment]
We use `master` branch as the stable version and develop branch is for upcoming feature development and once we release a version, the master branch will hold the latest stable code.

**Comment by rousan** [comment]
If we could re-export the `bytes` crate fully instead of just `Bytes` struct, how would it be?

**Comment by Koxiaet** [comment]
> If we could re-export the `bytes` crate fully instead of just `Bytes` struct, how would it be?

Yeah, that would also be good. Probably even better because users can get everything from the bytes crate.

**Comment by rousan** [comment]
Okay, then, let's re-export the `bytes` crate and update the PR, I will merge.

**Review by rousan — APPROVED** [review]

**Pull request merged**
